Makefile: pass -lsystemd last
Otherwise compilation Ubuntu 18.04 (which is what Github Actions uses)
fails horribly:

cc  -Wall -Wextra -Wformat-security -Wconversion -fstack-protector-all -std=gnu99 -lsystemd -g -o systembus-notify *.c
/tmp/ccbN2iDZ.o: In function `handle_signal':
/home/runner/work/systembus-notify/systembus-notify/main.c:19: undefined reference to `sd_bus_message_read_basic'
/home/runner/work/systembus-notify/systembus-notify/main.c:27: undefined reference to `sd_bus_message_read_basic'
/tmp/ccbN2iDZ.o: In function `main':
/home/runner/work/systembus-notify/systembus-notify/main.c:43: undefined reference to `sd_bus_default_user'
/home/runner/work/systembus-notify/systembus-notify/main.c:52: undefined reference to `sd_bus_default_system'
/home/runner/work/systembus-notify/systembus-notify/main.c:61: undefined reference to `sd_bus_add_match'
/home/runner/work/systembus-notify/systembus-notify/main.c:69: undefined reference to `sd_bus_process'
/home/runner/work/systembus-notify/systembus-notify/main.c:79: undefined reference to `sd_bus_wait'
/tmp/ccVupMIB.o: In function `notify':
/home/runner/work/systembus-notify/systembus-notify/notify.c:13: undefined reference to `sd_bus_message_new_method_call'
/home/runner/work/systembus-notify/systembus-notify/notify.c:24: undefined reference to `sd_bus_message_append'
/home/runner/work/systembus-notify/systembus-notify/notify.c:36: undefined reference to `sd_bus_message_unref'
/home/runner/work/systembus-notify/systembus-notify/notify.c:39: undefined reference to `sd_bus_call'
/home/runner/work/systembus-notify/systembus-notify/notify.c:40: undefined reference to `sd_bus_message_unref'
collect2: error: ld returned 1 exit status
make: *** [systembus-notify] Error 1
Makefile:4: recipe for target 'systembus-notify' failed